#if !canImport(ObjectiveC)
import XCTest

extension RedisTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisTests = [
        ("testStub", testStub),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RedisTests.__allTests__RedisTests),
    ]
}
#endif
